version: '3.9'

services:
  jsbluetoothprint:
    container_name: jsbluetoothprint
    image: webserver_8_2
    hostname: jsbluetoothprint
    ports:
      - 8921:80
    networks:
      - devnetwork
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./../:/var/www/html:consistent
    working_dir: /var/www/html

networks:
  devnetwork:
    name: devnetwork
    external: true